### ISSUE TITLE
Unable to push afer calling [[SlideNavigationController sharedInstance] popToRootViewControllerAnimated:YES];

### ISSUE THREAD

**Issue by JoshNussbaum** [aryaxt/iOS-Slide-Menu#105]
I have a right menu with a settings and logout button. When I click settings, I close the menu, set a conditional, and from my home screen I push segue to a settings view controller.

For the logout button, I call [[SlideNavigationController sharedInstance] popToRootViewControllerAnimated:YES]; function to go back to my login screen.

If I logout, then log back in and try to go to Settings from the right menu I run into an error: Terminating app due to uncaught exception 'NSGenericException', reason: 'Could not find a navigation controller for segue 'home_to_settings'. Push segues can only be used when the source controller is managed by an instance of UINavigationController.

When I change the segue to a modal segue I get this error:
 Warning: Attempt to present <SettingsViewController: 0x7fe1e2c51150> on <HomeViewController: 0x7fe1e063e620> whose view is not in the window hierarchy!

So, it seems like the Home view controller is no longer on the window hierarchy, or the navigation stack. I'm not really sure.

**Comment by aryaxt** [comment]
My guess is you are keeping a reference to HomeViewController which has been popped out of the nav controller, on the next login you are instantiating another HomeViewController. The one you are calling push from is the old one you are referencing rather than the new one in the stack.
in viewDidLoad of the HomeViewController do NSLog(@"%@", self) . I bet the memory location showing is not the same as the one in the exception


Don't keep a reference to HomeViewController, inside the menu. Just push it into the navigationController as a new instance every time login is successful.

**Comment by JoshNussbaum** [comment]
I do have different memory locations when I print NSLog(@"%@", self) both times I log in. 

However, I don't believe I'm keeping a reference to the HomeViewController. From the right menu I'm now settings a boolean and calling     
[[SlideNavigationController sharedInstance]closeMenuWithCompletion:^{
    }];
then in the HomeViewControllerI call   [[SlideNavigationController sharedInstance] popToRootViewControllerAnimated:YES];
When I log in, I'm calling a segue from the LoginViewController to the HomeViewController. Then, when I go to settings I am closing the right menu and calling a segue from HomeViewController to SettingsViewController based on another conditional. As far as I know, the HomeViewController should be getting popped off the navigation stack and I should be instantiating another one. Do you know why this wouldn't be happening?

**Comment by aryaxt** [comment]
It's hard to tell without seeing the code. Take a look at the demo. This exact functionality is in the demo

**Comment by JoshNussbaum** [comment]
In the code though, you never call a segue from home to another view controller when you use a slide menu button. In the examples you are poppingToRoot and switching, which in this case would cause my users to log out to go to a different screen

**Comment by aryaxt** [comment]
Can you provide some code?

**Comment by JoshNussbaum** [comment]
Sure,
So in the storyboard i have a push segue from login to home. I have the left and right slide menus part of home. From the right menu, when I click the logout button, I call

**Comment by JoshNussbaum** [comment]
Sure,
So in the storyboard i have a push segue from login to home. I have the left and right slide menus part of home. From the right menu, when I click the logout button, I call

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
	switch (indexPath.row)
	{

            case 2:
                [self.tableView deselectRowAtIndexPath:[self.tableView indexPathForSelectedRow] animated:YES];
                currentUser = [user getInstance];
                currentUser.showSettings = YES;
                [[SlideNavigationController sharedInstance]closeMenuWithCompletion:^{
                }];
			break;
	   case 3:
                [self.tableView deselectRowAtIndexPath:[self.tableView indexPathForSelectedRow] animated:YES];
                    currentUser = [user getInstance];
                    currentUser.loggingOut = YES;
                    [[SlideNavigationController sharedInstance]closeMenuWithCompletion:^{
                     }];
                return;
                break;
            
	     default:
			return;
	}
}

then in home I call    
 [[NSNotificationCenter defaultCenter] addObserverForName:SlideNavigationControllerDidClose object:nil queue:nil usingBlock:^(NSNotification *note) {
        [self menuClosed];
    }];
which i set up my in viewDidLoad, which calls a segue from the function menuClosed to another viewController based on the conditionals. 

So, I actually figured out the error in explaining this. When I logout, I have to remove the Notification Center observer for menu closed, as that observer no longer exists once the home view controller is popped. So I created an NSNotificationCenter object for the observer and remove it when I log out. 

Thanks for the help man

**Comment by aryaxt** [comment]
Cool that was a tricky one
