### ISSUE TITLE
how to use UITabBarController in iOS-Slide-Menu?

### ISSUE THREAD

**Issue by leiyong316** [aryaxt/iOS-Slide-Menu#106]
initial view Controller is SlideNavigationController in storyboard,  I want to initial view Controller is UITabBarController, how to use?

![image](https://cloud.githubusercontent.com/assets/2143362/5755120/b338b82a-9cdb-11e4-91ce-b3a0cb90d34d.png)
![image](https://cloud.githubusercontent.com/assets/2143362/5755130/c513e42a-9cdb-11e4-9ee3-0cae49f4a07c.png)

**Comment by aryaxt** [comment]
SlideNavigationController was built to work as a singleton. If you want to have multiple in the tabbar  you should modify the code

**Comment by leiyong316** [comment]
thanks

**Comment by marcelghisi** [comment]
Same error same image, before to add second navigationcontroller for second item

**Comment by fgboalt** [comment]
I am also using a UITabBarController and added the iOS-Slide-Menu to my project,... to a single tab. The problem I am seeing is that the LeftMenuViewController, which contains a UITableView gets no input or scrolling. Any ideas? Thanks.

**Comment by Bhawin21** [comment]
how to use tabbarcontroller with this library [Objective c] ? any solution ?
