### ISSUE TITLE
How may I use this lib without Storyboard?

### ISSUE THREAD

**Issue by lkmmmj** [aryaxt/iOS-Slide-Menu#108]
The App I am working on has no storyboard, how may I use this lib without storyboard?

**Comment by aryaxt** [comment]
[[SlidNavigationController alloc] initWithRootViewController:SOME_VC];

Then set it as the rootViewController of the windeow

**Comment by lkmmmj** [comment]
Thank you!

**Comment by seanLee** [comment]
''''SlideNavigationController *root = [[SlideNavigationController alloc] initWithRootViewController:[[AlbumMainViewController alloc] init]];
    PersonalManagementViewController *pmvc = [[PersonalManagementViewController alloc] initWithNibName:@"PersonalManagementViewController" bundle:nil];
    //背景图片
    UIColor *bgColor = [UIColor colorWithPatternImage: [UIImage imageNamed:@"back_bottom"]];
    [pmvc.view setBackgroundColor:bgColor];
    [SlideNavigationController sharedInstance].leftMenu = pmvc;
    
    [self.window setRootViewController:root];````

that'a how I use this lib.But it didn't.How can I make it working?

**Comment by seanLee** [comment]
````
SlideNavigationController *root = [[SlideNavigationController alloc] initWithRootViewController:[[AlbumMainViewController alloc] init]];
PersonalManagementViewController *pmvc = [[PersonalManagementViewController alloc] initWithNibName:@"PersonalManagementViewController" bundle:nil];
//背景图片
UIColor *bgColor = [UIColor colorWithPatternImage: [UIImage imageNamed:@"back_bottom"]];
[pmvc.view setBackgroundColor:bgColor];
[SlideNavigationController sharedInstance].leftMenu = pmvc;

[self.window setRootViewController:root];
````
that'a how I use this lib.But it didn't.How can I make it working?

**Comment by seanLee** [comment]
have solved this problem.

**Comment by badalpub1991** [comment]
@seanLee  how you have solved the problem ?? i want to change the root view controller when user had done login and without login. can you help me please ?
