### ISSUE TITLE
Change title of left or rightmenu?

### ISSUE THREAD

**Issue by D33jay** [aryaxt/iOS-Slide-Menu#109]
First of all great work. The Slide menu is really great and well programmed. It saved me a lot of time..
Is it possible to change the navigationbar title of the left or rightmenu? I tried self setTitle, set it in Storyboard and set a navigationItem, but nothing works.

**Comment by aryaxt** [comment]
Glad you found it helpful. Yes it's possible, you need to wrap the menuViewController inside a navigation controller, and instead of setting the menuViewController, set the navigationController as the left/right menu.

**Comment by D33jay** [comment]
Thanks for your quick answer. Unfortunately, when i wrap my menu in a navigationController (Storyboard) and I write [SlideNavigationController sharedInstance].leftMenu = leftMenu.navigationController, the navigationController is nil. And when i instantiate the navigationcontroller and store it as the leftmenu the title is displayed, but the whole leftMenus position starts below another navigationbar (or just a navigationbars height). Which is really strange, because the navigationbar which is under the title bar has the right color. Any suggestions? Maybe I missunderstood your answer :)
![img_3013](https://cloud.githubusercontent.com/assets/2698685/5818285/a9f47ccc-a0b4-11e4-8427-10b422fc007d.PNG)

**Comment by aryaxt** [comment]
You can't do that, give that nav controller an identifier and load that instead of loading leftMenu directly.

If this is not easily implemented you could simply design your menu to look like it has a nav bar

**Comment by D33jay** [comment]
I did that but unfortunately i got the effect with these two navigationbars I mentioned before :(

My code looks like this:

  UINavigationController *navigationViewController = [MCStoryboardIPhone instantiateViewControllerWithIdentifier:@"nc"];
 [SlideNavigationController sharedInstance].leftMenu = navigationViewController;

maybe I try to design it like there is a navigationbar

**Comment by D33jay** [comment]
Ok, it was my fault. I added a Big Section Header onto the top with the same height as a navigationbar. I did this in the past and totally forgot about it :). And I was wondering why there was two Navigationbars :) Sorry...

**Comment by shinurag** [comment]
Hello... 
my AppDelegate.m looks like this


```
UIViewController *viewController = [[NSClassFromString(@"VCDashboard") alloc] initWithNibName:@"VCDashboard" bundle:nil];

    // Changing UI appearance
[[UINavigationBar appearance] setBackgroundImage:[UIImage imageNamed:@"navBkgnd.png"] forBarMetrics:UIBarMetricsDefault];
    
    NSDictionary *navBarTitleTextSetting = [NSDictionary dictionaryWithObjectsAndKeys:
                                            //[UIColor colorWithRed:175.0f/256.0f green:219.0f/256.0f blue:74.0f/256.0f alpha:1.0f], NSForegroundColorAttributeName,
                                            [UIColor orangeColor],NSForegroundColorAttributeName,
                                            [UIFont fontWithName:@"Capsuula" size:23.0f], NSForegroundColorAttributeName,
                                            nil];
    [[UINavigationBar appearance] setTitleTextAttributes:navBarTitleTextSetting];
    

    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    // Override point for customization after application launch.
    self.window.backgroundColor = [UIColor whiteColor];
    SlideNavigationController *navigationController = [[SlideNavigationController alloc] initWithRootViewController:viewController];
    navigationController.navigationBar.translucent = YES;
    self.window.rootViewController = navigationController;
    
    [self.window makeKeyAndVisible];
    
    [UIApplication sharedApplication].statusBarHidden = YES;
    
//    LeftMenuViewController *leftMenu = (LeftMenuViewController*)[[NSClassFromString(@"VCLeftmenu") alloc] initWithNibName:@"VCLeftmenu" bundle:nil];
//    RightMenuViewController *rightMenu = (RightMenuViewController*)[[NSClassFromString(@"VCRightmenu") alloc] initWithNibName:@"VCRightmenu" bundle:nil];
    
    VCLeftmenu *leftMenu = (VCLeftmenu *)[[NSClassFromString(@"VCLeftmenu") alloc] initWithNibName:@"VCLeftmenu" bundle:nil];
    VCRightmenu *rightMenu = (VCRightmenu *)[[NSClassFromString(@"VCRightmenu") alloc] initWithNibName:@"VCRightmenu" bundle:nil];

    
    [SlideNavigationController sharedInstance].rightMenu = rightMenu;
    [SlideNavigationController sharedInstance].leftMenu = leftMenu;
    
//    [SlideNavigationController sharedInstance].menuRevealAnimator = [[SlideNavigationContorllerAnimatorSlideAndFade alloc] initWithMaximumFadeAlpha:.8 fadeColor:[UIColor blackColor] andSlideMovement:100];;
    
    // Creating a custom bar button for right menu
    UIButton *button  = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
    [button setImage:[UIImage imageNamed:@"right_menu"] forState:UIControlStateNormal];
    [button addTarget:[SlideNavigationController sharedInstance] action:@selector(toggleRightMenu) forControlEvents:UIControlEventTouchUpInside];
    UIBarButtonItem *rightBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:button];
    [SlideNavigationController sharedInstance].rightBarButtonItem = rightBarButtonItem;
    
    // Creating a custom bar button for left menu
    UIButton *buttonleft  = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
    [buttonleft setImage:[UIImage imageNamed:@"left_menu"] forState:UIControlStateNormal];
    [buttonleft addTarget:[SlideNavigationController sharedInstance] action:@selector(toggleLeftMenu) forControlEvents:UIControlEventTouchUpInside];
    UIBarButtonItem *leftBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:buttonleft];
    [SlideNavigationController sharedInstance].leftBarButtonItem = leftBarButtonItem;
```

and i write the code VCLeftmenu.m
```
    UILabel *titleLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, 320, 30)];
    titleLabel.textColor = [UIColor redColor];
    titleLabel.backgroundColor = [UIColor yellowColor];
    titleLabel.text = @"My Title";
    [self.navigationItem setTitleView:titleLabel];
```
for showing the title menu of the topbar but the title not showing on this ViewController

Note: I'm not using Storyboard.

Thank you
Shinurag KR

**Comment by shinurag** [comment]
Anyone here?? pls help me out.
