### ISSUE TITLE
interfaceOrientation is deprecated

### ISSUE THREAD

**Issue by MehranZand** [aryaxt/iOS-Slide-Menu#116]
I get this error after build.

'interfaceOrientation' is deprecated: first deprecated in iOS 8.0

thanks in advance

**Comment by MehranZand** [comment]
additional info : base sdk 8.1 and target 8.1

**Comment by aryaxt** [comment]
Will look into this, thanks

**Comment by enzoses** [comment]
Same here, I got 12 warnings

**Comment by sisuc** [comment]
I waiting for your fix too.

**Comment by jonasman** [comment]
+1

**Comment by aryaxt** [comment]
Fixed in 1.4.6 and pushes to CocoaPods
