### ISSUE TITLE
viewDidappear is just called once

### ISSUE THREAD

**Issue by klinkert0728** [aryaxt/iOS-Slide-Menu#118]
Hi

There's a way to change the content of the SlidenavigationController each time you open it?

I'm trying change the content in viewDidAppear but this method is just called one time 

Thank you

**Comment by aryaxt** [comment]
That's expected because menu is no inside a UINavigationController, and it's not the root either.

Use one of the notifications: https://github.com/aryaxt/iOS-Slide-Menu#notifications
