### ISSUE TITLE
slide menu fails to initialize once I leave the view controller

### ISSUE THREAD

**Issue by german-borys** [aryaxt/iOS-Slide-Menu#121]
Im having issues with the slide out menu when I leave the view controller that houses the slideNavigationController. Im using SlideNavigationController in one of my tab view controllers and when I leave it and return, the slide out menu comes up blank (black background with no elements). Any ideas as to how I can fix that? Thanks

**Comment by ahmad-raza** [comment]
What was the issue? How did you fix it? 
I'm facing it

**Comment by german-borys** [comment]
I think I fixed it by adding a third method to the default two:
- (BOOL)slideNavigationControllerShouldDisplayLeftMenu
{
    return NO;
}

- (BOOL)slideNavigationControllerShouldDisplayRightMenu
{
    return YES;
}
//This one did smthn, there isnt much documentation so its not clear
- (BOOL)avoidSwitchingToSameClassViewController{
    return NO;
}

Also, I passed objects to my side menu so the issue I had dealt with initializing side menu instead of updating an existing instance. I fixed it by creating a method that would update the menu if it already existed, and initializing it when it didnt. Hope this helps. Im actually still having problems when I try to use different menu classes for different view controllers, I keep getting a blank side menu when initializing a new side menu with a different class.

**Comment by k4roshi** [comment]
Removing those two rows seem to fix this:
````
// Only prepare menu if it has changed (ex: from MenuLeft to MenuRight or vice versa)
if (self.lastRevealedMenu && menu == self.lastRevealedMenu)
  return;
````
Are they strictly necessary?

**Comment by german-borys** [comment]
no, they are not. You can make it work without those two lines

**Comment by aryaxt** [comment]
@k4roshi  Those 2 lines are there to avoid glitches in the animations. If you are not using an animation you don't need that code. I can't reproduce the issue, but if you post a sample I would be happy to take a look

**Comment by german-borys** [comment]
yeah, my animations work fine, but Im just using the regular slide out and
drag animations. I might post a sample of my code once I get some free
time.

**Comment by MMasterson** [comment]
+1 this solved my problem as well
