### ISSUE TITLE
Slide Menu content not reload 

### ISSUE THREAD

**Issue by Pelletan** [aryaxt/iOS-Slide-Menu#122]
Hi !

I'm trying to integrate iOS-Slide-Menu and it works well !

However, i have 3 differents VC (MovieVC, ClipVC, TeaserVC).
All of these VC use the same classe class (VideoTableViewController), however they all have a specific identifier.

When im trying to access to ClipVC after MovieVC with popToRootAndSwitchToViewController , my VC is lot loaded.

I think it's because they all use the same classe.

How can i acces to different VC with a specific identifier, and the same class ?

**Comment by aryaxt** [comment]
Set avoidSwitchingToSameClassViewController to false

**Comment by Pelletan** [comment]
That works !

Thank you :+1: !!!
