### ISSUE TITLE
How to set title of leftBarButtonItem empty 

### ISSUE THREAD

**Issue by q0988113683** [aryaxt/iOS-Slide-Menu#130]
The next view controller's leftBarButtonItem title always show previous view controller's title,when the  view controller push to next view controller.

https://dl.dropboxusercontent.com/u/20710433/Screen%20Shot%202015-03-25%20at%203.00.23%20PM.png

https://dl.dropboxusercontent.com/u/20710433/Screen%20Shot%202015-03-25%20at%203.00.30%20PM.png

i tried to set on next view controller
self.navigationItem.leftBarButtonItem.title = @"";
but it's not working,
Does anyone know how to solve it?

**Comment by aryaxt** [comment]
https://github.com/aryaxt/iOS-Slide-Menu/issues/109
