### ISSUE TITLE
How does a VC get a notification when a side is about to open/close?

### ISSUE THREAD

**Issue by jonasman** [aryaxt/iOS-Slide-Menu#131]

**Comment by aryaxt** [comment]
https://github.com/aryaxt/iOS-Slide-Menu#notifications

**Comment by jonasman** [comment]
Right. Sorry :)

Read the guide until costume animations only!

Enviado do meu iPhone

No dia 25/03/2015, às 19:49, Aryan Ghassemi <notifications@github.com> escreveu:

**Comment by aryaxt** [comment]
No worries :)
