### ISSUE TITLE
Dealloc is not getting called

### ISSUE THREAD

**Issue by hagile** [aryaxt/iOS-Slide-Menu#136]
I'm using this in one of my app. When I tap sign out in left menu, I'm changing rootviewcontroller of the app. Thought it ll never change dealloc method of  any of the view controllers? What's wrong?

**Comment by aryaxt** [comment]
Will look into that

**Comment by aryaxt** [comment]
Take a look at the demo project, dealloc gets called correctly on popping viewcontrollers properly. You may have retain cycles
