### ISSUE TITLE
Complete view is reverse in iOS7

### ISSUE THREAD

**Issue by kaseriya** [aryaxt/iOS-Slide-Menu#138]
Hi,
Thank you for this awesome lib, it works great with iOS8 but i see there is a big issue with iOS7. The complete view is reverse for both left and right menu. Please look into this.

**Comment by aryaxt** [comment]
What's the deployment target on the project? If not 8 can you set it to 8 and see if it resolves the issue?

**Comment by kaseriya** [comment]
with the deployment target 8 i can run this project only on iOS 8 and its working fine with that but if set deployment target 7 and run this project on iOS 7 then i see following issues

Swipe Gestures are in opposite direction. (left menu is on the right side and right menu is on the left side) and the menu views are also in reverse direction.

**Comment by hnchan** [comment]
I have same problem as well.

**Comment by kaseriya** [comment]
The is not reproducible in actual device (iPad Air with iOS 7 in my case) in "Portrait Mode" but it reproduces with "Landscape Mode" in same device.

In iOS 7 Simulator, this issue is reproducible in both the mode.

**Comment by aryaxt** [comment]
Thanks for the info, will look into it

**Comment by ollieatkinson** [comment]
Reverting back to 1.4.5 for the time being works if you still need to deploy to iOS 7

**Comment by TayfunAslan** [comment]
Same issues for me, on iOS 7 device & simulator

**Comment by limouren** [comment]
7fb3ec0 won't solve the issue since it used the device orientation. If a device is face up / face down the detection will fault.

I hope @aryaxt will re-consider @wtimme PR because that's the way to properly detect UI orientation on iOS < 8.0. If deprecated warning is a concern, we can call it using selector.

**Comment by aryaxt** [comment]
@limouren That PR is exactly what there was before getting rid of interface orientation warnings. You could point your pod to that version. (version 1.4.5)

**Comment by sureshkansujiya** [comment]
AnyBody Solve the issue for iOS 7 Please  share here ...

**Comment by wtimme** [comment]
We've forked the project and added the changes from the PR that I proposed. I do care about warnings, but I'd rather have some warnings than a non-functional menu (no offense!).

**Comment by aryaxt** [comment]
@wtimme "That PR is exactly what there was before getting rid of interface orientation warnings. You could point your pod to that version. (version 1.4.5)"

**Comment by evgeniyd** [comment]
We had this issue in our project as well. What I have discovered is that `[[UIDevice currentDevice] orientation] == UIDeviceOrientationUnknown` sometimes.
Based on [this SO answer ](http://stackoverflow.com/a/11996096) the orientation has to be validated before use.
I have a fix for this in my fork.

**Comment by aryaxt** [comment]
@evgeniyd correct, I think it would also be nice to detect any valid device orientation change and store it and use it for calculations. This way when the device goes face-up or face-down we still know what the last  valid orientation was.

**Comment by evgeniyd** [comment]
@aryaxt yeah, sounds good. So far, I sorted it out by fallback to Portrait orientation in case `currentDevice` returns `Unknown`. Please, take a look at the pool request.

**Comment by gd250** [comment]
so what i need to do for make it works on IOS7  ? ( i have the smae issue )

**Comment by evgeniyd** [comment]
@gd250 you can grab my fork's `fix-slides-from-opposite-side` branch which has a hot-fix for this. Note, though, that this is a hammer, as @aryaxt mentioned there are more places where `[[UIDevice currentDevice] orientation]`'s value is read and it would be better to be more smart about using it. For now, check out that change as a temporary solution.

@aryaxt what do you think? Thanks.

*Podfile:*
```
pod 'iOS-Slide-Menu', :git => 'https://github.com/evgeniyd/iOS-Slide-Menu', :branch => 'fix-slides-from-opposite-side'
```

**Comment by aryaxt** [comment]
@gd250 If you support both landscape and portrait use 1.4.5, otherwise use 1.4.6
The PR still needs work. right now it assumes an unknown orientation is portrait which is incorrect.

**Comment by aryaxt** [comment]
Version 1.5 should be available with the fix.
Please let me know if you have any problems
