### ISSUE TITLE
different portraitSlideOffset for left and right menu?

### ISSUE THREAD

**Issue by maciejburda** [aryaxt/iOS-Slide-Menu#139]
Is it possible to set diffrent portraitSlideOffset for left and right menu?

**Comment by aryaxt** [comment]
This feature isn't there, but you could listen for menu reveal notification, and based on the menu being revealed (in userInfo of notification) update the portraitSlideOffset value

**Comment by maciejburda** [comment]
I did it like this in app delegate:

[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(changeSlidingMenuOffset:) name:SlideNavigationControllerDidReveal object:nil];
}

- (void)changeSlidingMenuOffset:(NSNotification*)notification {
    if ([notification.userInfo[@"menu"] isEqualToString:@"left"]) {
        [SlideNavigationController sharedInstance].portraitSlideOffset = [UIScreen mainScreen].applicationFrame.size.width - 250;
    }
    else {
        [SlideNavigationController sharedInstance].portraitSlideOffset = [UIScreen mainScreen].applicationFrame.size.width - 60;
    }
}

the problem is it doesn't with the first usage (takes default value).

Any ideas?

**Comment by maciejburda** [comment]
@drumbart is working it out. Merge request coming soon.
