### ISSUE TITLE
Push segue???

### ISSUE THREAD

**Issue by SadhuRus** [aryaxt/iOS-Slide-Menu#143]
Why left menu not working after push-segue to another viewController?

**Comment by aryaxt** [comment]
How is it not working? Not showing?

**Comment by SadhuRus** [comment]
Yes. After push segue i try to swipe left/right but menu not showed =(

**Comment by aryaxt** [comment]
you need to implement the delegate in every controller that needs it to be visible
```
- (BOOL)slideNavigationControllerShouldDisplayLeftMenu
{
        return YES;
}
```

**Comment by SadhuRus** [comment]
After it "back button" change to "menu" icon. And i can't go back.

**Comment by SadhuRus** [comment]
All Work if i comment this:

/*
- (void)navigationController:(UINavigationController *)navigationController
	  willShowViewController:(UIViewController *)viewController
					animated:(BOOL)animated
{
	if ([self shouldDisplayMenu:MenuLeft forViewController:viewController])
     viewController.navigationItem.leftBarButtonItem = [self barButtonItemForMenu:MenuLeft];
	
	if ([self shouldDisplayMenu:MenuRight forViewController:viewController])
		viewController.navigationItem.rightBarButtonItem = [self barButtonItemForMenu:MenuRight];
}

*/

**Comment by aryaxt** [comment]
Great, but if you comment that out, it'll always show the menu on any viewController, if that's the expected behavior for you, great

**Comment by SadhuRus** [comment]
That's the expected behavior for me. Thank you
