### ISSUE TITLE
SlideNavigationController not called as initial controller

### ISSUE THREAD

**Issue by outoftrun** [aryaxt/iOS-Slide-Menu#151]
I would like to have the SlideNavigationController called from a button rather than as the initial storyboard item.

 I have changed the demo code around so the singletonInstance is initilize from the button correctly and only once, everything come up looking correct but the left and right menu do not respond to touches. Do have a clue as to what I am doing wrong. I do have images of the menu items not responeding but thought better about sending them.

Nick

**Comment by aryaxt** [comment]
Duplicate https://github.com/aryaxt/iOS-Slide-Menu/issues/147#issuecomment-104016689
