### ISSUE TITLE
Customize title view on iOS 7.1

### ISSUE THREAD

**Issue by nvnguyenit** [aryaxt/iOS-Slide-Menu#156]
Hi man!

I user your lib, it's so great control... I customize a UIView and embed this view in title view (self.navigationItem.titelView= customview). It's working on iOS 8 but not in iOS7.1. Can you help me!

Best regard,

Nguyen

**Comment by timbodeit** [comment]
First of all, it's `titleView`, not `titelView`.

Did the menubar work at all in iOS 7? I also had issues under iOS 7, though I'm not sure if they are related. Have a look at #210 and see if that might help.

**Comment by aryaxt** [comment]
@nvnguyenit This lib doesn't do anything with title or titleView. Does this issue happen if you use a standard UINavigationController?

**Comment by aryaxt** [comment]
Can you confirm that the PR by @timbodeit fixes the issue? If yes, I'll merge it and push a new version

**Comment by timbodeit** [comment]
@aryaxt Correct. It doesn't touch title or titleView directly. These attributes are however a part of the navigationItem, that iOS-Slide-Menu does some work with.
I'm not saying, that I'm sure my PR will resolve @nvnguyenit s issue ... but it sure sounded a bit similar to the problems, that I was experiencing.

**Comment by nvnguyenit** [comment]
@aryaxt thanks for your time, i have fixed it. It conflict with another custom control i use. Sorry man, your control still good!

**Comment by timbodeit** [comment]
@aryaxt Guess this issue can be closed.
Still wouldn't mind if took a quick look at my pull requests, though ;)
