### ISSUE TITLE
Reload menu items 

### ISSUE THREAD

**Issue by Signoo** [aryaxt/iOS-Slide-Menu#163]
Hi,
I need to enable/disable a `UITableViewCell` of the menu if the user is logged or not. The problem is that the menu is created only once on the appDelegate and the method `cellForRowAtIndexPath` doesn't get called anymore so I can't edit that single `UITableViewCell`.
Is there a method to force the reload of the `UITableView`?

**Comment by Karov28** [comment]
just do :

[tableView reloadData];

**Comment by Signoo** [comment]
yeah but where?

**Comment by aryaxt** [comment]
https://github.com/aryaxt/iOS-Slide-Menu#notifications
