### ISSUE TITLE
How to add multiple button to the left side menu

### ISSUE THREAD

**Issue by sahabe1** [aryaxt/iOS-Slide-Menu#164]
Hi aryaxt,

I want to add multiple button to the left menu on the navigation bar can we add.
please help us how we can add multiple button please see attachment

Thanks
![ios simulator screen shot jun 23 2015 11 24 59 am](https://cloud.githubusercontent.com/assets/1065015/8299796/df0e5310-199a-11e5-84ec-6e25277a929d.png)

**Comment by aryaxt** [comment]
This code creates a side menu button
```
UIButton *button  = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
[button setImage:[UIImage imageNamed:@"menu-button"] forState:UIControlStateNormal];
[button addTarget:[SlideNavigationController sharedInstance] action:@selector(toggleRightMenu) forControlEvents:UIControlEventTouchUpInside];
UIBarButtonItem *rightBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:button];
```

in viewDidLoad
```
self.navigationItem.rightBarButtonItems = @[rightBarButtonItem,anotherButton];
```
