### ISSUE TITLE
canEditRowAtIndexPath not working

### ISSUE THREAD

**Issue by kalvish21** [aryaxt/iOS-Slide-Menu#166]
I"m not able to show the delete button on a row. Is this a known issue?

**Comment by kalvish21** [comment]
I realized the problem was this method was removed:

-(BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    return YES;
}


Was there a reason for this? What were the issues that were experienced with it? Seems to work for me.

**Comment by aryaxt** [comment]
there is another bug closed related to this, turning that on changes the behavior of gesture recognizer. For instance I don't want swipe to top followed by right to move the menu. If you turn it off/on and play with the menu (sliding open and close) you'll see this behavior, it's really hard to explain
