### ISSUE TITLE
How can I set the menu Orientation portrait only?

### ISSUE THREAD

**Issue by dhekrazaied** [aryaxt/iOS-Slide-Menu#169]
Hi,
On ipad even I set orientation to portrait on my app, the menu still rotate.
How can I set rotation false?

**Comment by jcarnerolopez** [comment]
Have the same issue. Any idea of how to solve this?

**Comment by dhekrazaied** [comment]
In the class slideNavigation.m set any occurrences of uiinterfaceDevice to uiinterfaceDevicePortrait

**Comment by aryaxt** [comment]
will look into this and add a fix if needed
Thanks

**Comment by jcarnerolopez** [comment]
Thanx dhekrazaied. It worked for me. You have saved me a lot of time. I really appreciate.
Best regards.

**Comment by evgeniyd** [comment]
Hi,

The problem here is that `SlideNavigationController` rely on device's orientation, rather than interface orientation.
So, rather than using 
```
UIDeviceOrientation orientation = [UIDevice currentDevice].orientation;
```
the controller should use
```
UIInterfaceOrientation interfaceOrientation = self.interfaceOrientation;
```

I have implemented the change in my fork.

**Comment by aryaxt** [comment]
This is fixe in 1.5
