### ISSUE TITLE
Opens from Right Side instead of Left

### ISSUE THREAD

**Issue by Parth-Patoliya** [aryaxt/iOS-Slide-Menu#173]
implemented for left side menu and it works fine for all devices except i-phone 4 with os 7.1.2. 
Menu opens from right side instead of left.

**Comment by Arcrammer** [comment]
I can't even get it to open at all!

**Comment by aryaxt** [comment]
point your pod to "1.4.5"

**Comment by aryaxt** [comment]
duplicate: https://github.com/aryaxt/iOS-Slide-Menu/issues/138

**Comment by Arcrammer** [comment]
I just deleted the whole project. I'll start over because I really want to use this. I don't know if I'm the only one but the documentation and intro _really_ don't help me actually implement it at all.

**Comment by aryaxt** [comment]
fixed on 1.5
