### ISSUE TITLE
Exit to a new storyboard without navigation

### ISSUE THREAD

**Issue by Aleph72** [aryaxt/iOS-Slide-Menu#186]
Hello, 
I'm using iOS Slide Menu and so far I like it. 
There's one thing that I'm not able to figure out: by pressing a button in the left menu I need to switch to another storyboard that doesn't have a navigation controller.
If I do:

    UIStoryboard *currentStoryboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    HDLoginViewController *vc = [currentStoryboard instantiateViewControllerWithIdentifier:@"login"];
    [[SlideNavigationController sharedInstance] popAllAndSwitchToViewController:vc withSlideOutAnimation:YES andCompletion:nil];

the app moves to the storyboard I need, but it keeps the menu navigation controller.
Is there anyway to eliminate the navigation controller when switching storyboards?
Thanks.

**Comment by aryaxt** [comment]
Hide the navbar

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationController_Class/#//apple_ref/occ/instm/UINavigationController/setNavigationBarHidden:animated:

**Comment by Aleph72** [comment]
I tried, but the navbar is not a subview of the left menu, it's a subview of the home viewcontroller.

**Comment by aryaxt** [comment]
navbar is the subview of the navigationController, navigationcontroller is shared across the viewcontrollers in the stack
