### ISSUE TITLE
re-creates page

### ISSUE THREAD

**Issue by codaman** [aryaxt/iOS-Slide-Menu#200]
when open a menu item on left page, it creates this view controller again. Again it called viewDidload and kills last object. Don't need to re-create page before it created

**Comment by codaman** [comment]
facebook and another apps that have slide page like this, not re-create pages

**Comment by aryaxt** [comment]
try using avoidSwitchingToSameClassViewController
this feature doesn't need to be implemented on the menu, you could simply have a property and push an existing vc instead of creating a new vc

**Comment by SCLDev** [comment]
I used this and it worked like a charm.
