### ISSUE TITLE
deallocs popped viewController

### ISSUE THREAD

**Issue by codaman** [aryaxt/iOS-Slide-Menu#201]
When click another cell on left menu it deallocs previous view controller. In Facebook or another apps like this not re-creating pages. I tried avoidSwitchingToSameClassViewController feature but this only keeps clicking same viewController that already opened. For example you have 3 pages on left menu A,B,C. At the beginning it starts with A page when you click B it deallocs A and creates B. if avoidSwitchingToSameClassViewController is YES ,it only provides if B is opened already when you click B not re-creates B. i tried many frameworks ,only few frameworks that using xib not re-creating view controllers.  i'm trying to solve this problem, if i'm successful ,i sent pull request. i like this framework it is very clear coded. i want it have this feature.

**Comment by codaman** [comment]
i've created a stack mutableArray that insert created viewControllers to mutableArray so you don't need to re-create pages. i'm testing when i'll finish ,i'll send pull request

**Comment by aryaxt** [comment]
https://github.com/aryaxt/iOS-Slide-Menu/issues/200
