### ISSUE TITLE
Keep right menu after presentModal viewController

### ISSUE THREAD

**Issue by Lapinou42** [aryaxt/iOS-Slide-Menu#202]
Hello, 

I have an app with a right menu. I have to present a viewController, but keep the right menu working.
How can I do this ? Is it possible on a presented viewController ? 

Thank you for your help.
Regards,

**Comment by aryaxt** [comment]
look at `toggleLeftMenu` section in https://github.com/aryaxt/iOS-Slide-Menu and see if it works.
You need to manually create a button, or a bar button and have it to open/close the menu

**Comment by Lapinou42** [comment]
Thank you for your help aryaxt ;)

I've already try this solution. It works but not on a presented view controller.
The button is shown, the methods toggleRightMenu is correctly called but the menu doesn't opening.

I think it's because it's a presented view controller and I'm worried it's not possible :(
