### ISSUE TITLE
present a new controller problem

### ISSUE THREAD

**Issue by longtianye** [aryaxt/iOS-Slide-Menu#205]
when i click left page , i present a new controller ,but after dismiss my new controller, show home page, not left page, why? how can i solve this situation

**Comment by naumovkirill** [comment]
I have the same problem, please let us know if you find a solution

**Comment by gaoxiao228** [comment]
I have the same problem, please let us know if you find a solution

**Comment by MadBurea** [comment]
you will have to specify the class where you are using this left or write menu. change in this portion.
- (void)navigationController:(UINavigationController *)navigationController
    willShowViewController:(UIViewController *)viewController
                  animated:(BOOL)animated
  {
  if ([self shouldDisplayMenu:MenuLeft forViewController:viewController])
  {
      if ([viewController isKindOfClass:[ leftmenuClass class]])
      {
          viewController.navigationItem.leftBarButtonItem = [self barButtonItemForMenu:MenuLeft];
      }
  if ([self shouldDisplayMenu:MenuRight forViewController:viewController])
  
  if ([viewController isKindOfClass:[ rightMenuClass class]])
  {
  
  }
  }

**Comment by longtianye** [comment]
thanks, @MadBurea
