### ISSUE TITLE
change root view in between app?

### ISSUE THREAD

**Issue by maulikshah09** [aryaxt/iOS-Slide-Menu#240]
How can i change normal navigation to slide navigation in between app?

AppDelegate  did finish  code

```
  UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Storyboard" bundle:nil];
        LoginViewController *ivc = [storyboard instantiateViewControllerWithIdentifier:@"LoginView"];
        UINavigationController *navigationController=[[UINavigationController alloc] initWithRootViewController:ivc];
       
        self.window.rootViewController = navigationController; 
        [self.window makeKeyAndVisible];
```

form this code open login view .. after login i want to add this control?How can i do That? I know that following method... but i want to set this control  as rootview after login.

 
```
- (BOOL)slideNavigatonControllerShouldDisplayLeftMenu
{
        return YES;
}

```

**Comment by aryaxt** [comment]
why would you do that? SllideNavigationController is simply a subclass of UINavigationController, you can enable slide functionality where you need it instead of switching root

**Comment by maulikshah09** [comment]
i don't want slide button and swipe menu in login screen and address screen.. after login i want to side menu..dash board open everytime.

**Comment by maulikshah09** [comment]
Please help to figure out

**Comment by aryaxt** [comment]
please look at the demo, it has the exact scenario you are describing with a login screen

**Comment by fresh83** [comment]
Uh second the ability to use this without it being the initial root, for the purpose of keeping storyboards neatly separated into different sections of the app. For example, my onboard process is its own storyboard, so is my auth and then i have a main storyboard. To use your lib it feels, on first glance that i would have to rework my entire app to use what shows up as the #1 slide nav lib.
