### ISSUE TITLE
UITableViewCell delete gesture dosen't work

### ISSUE THREAD

**Issue by rowwingman** [aryaxt/iOS-Slide-Menu#27]
UITableViewCell scrollView dosen't work when trying to show delete confirmation button with swipe.

**Comment by martinprot** [comment]
Hi.
@nullproduction, It's not a problem with all swipe-sliders.
Use `gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:` delegate method to handle this problem.
For example, this implementation fix the problem:

```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
	return YES;
}
```

But maybe it's too simple, i think the controller should give a method to better control this.

**Comment by marioacarvalho** [comment]
@nullproduction thanks. It fixes
