### ISSUE TITLE
The Slide Menu dissappear when I give an action  to button in tableView  

### ISSUE THREAD

**Issue by klinkert0728** [aryaxt/iOS-Slide-Menu#44]
EveryThing Works perfect but when I add an action to my button, everything  dissappear 
 in my navigationBar.  maybe you can help me.

this is the button with the action
![captura de pantalla 2014-05-20 a la s 12 50 44 pm](https://cloud.githubusercontent.com/assets/6820828/3031030/b7d1db2e-e047-11e3-8f67-ac200ee5a99a.png)

this is the button without an action.
![captura de pantalla 2014-05-20 a la s 12 51 06 pm](https://cloud.githubusercontent.com/assets/6820828/3031040/c8bc014e-e047-11e3-9ff6-d5dea227f336.png)

**Comment by aryaxt** [comment]
Do you happen to use MBProgressHUD?
Calling hideHUDForView:self on MBProgressHUD removes subviews of UIWIndow which also includes the menu

**Comment by aryaxt** [comment]
@klinkert0728 I'm guessing MBProgressHUD was the issue. Can you verify?

Thanks
