### ISSUE TITLE
Singleton instance already exists.

### ISSUE THREAD

**Issue by klinkert0728** [aryaxt/iOS-Slide-Menu#45]
I have a logout button, when i press this button the user should log in again, when the user log in correctly this message appears 
"Singleton instance already exists. You can only instantiate one instance of SlideNavigationController. This could cause major issues".

I know why that's happen but i don't know how to remove the slideNavigationCntroller instance when the user press Logout

Hope you can help me

**Comment by prabhums** [comment]
Im still seeing this warning message. Is there any update?
