### ISSUE TITLE
Navigation bar title and buttons not shown

### ISSUE THREAD

**Issue by orenk86** [aryaxt/iOS-Slide-Menu#61]
Hey,
The "sliding navigation controller" in my app is not the initial view controller in the app. I set it up at the first time it appears, and it works fine.
Only problem is, I can't seem to get the navigation bar's title and buttons to show. The navigation bar keeps appearing empty.

I run this code in the "viewDidLoad" method of the first navigation controller that is embedded in the "sliding navigation controller":

```
// setup side menu
ICContentMenuViewController *contentMenu = [self.storyboard instantiateViewControllerWithIdentifier:@"menuController"];
[SlideNavigationController sharedInstance].leftMenu = contentMenu;
self.navigationController.view.backgroundColor = [UIColor whiteColor];
[SlideNavigationController sharedInstance].rightBarButtonItem = leftBarButtonItem;
self.navigationItem.title = @"Browse";

// Creating a custom bar button for left menu
UIButton *button  = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
[button setImage:[UIImage imageNamed:@"MenuIcon"] forState:UIControlStateNormal];
[button addTarget:[SlideNavigationController sharedInstance] action:@selector(toggleLeftMenu) forControlEvents:UIControlEventTouchUpInside];
UIBarButtonItem *leftBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:button];
```

The menu gets set and loads fine, and the background color gets set, but no title and no button.
I also tried setting the title from the storyboard, but no luck... any idea what I'm missing here?

**Comment by KigenCoder** [comment]
Any solution on this even on subsequent versions??
