### ISSUE TITLE
How to use SlideMenu with tabbar application? 

### ISSUE THREAD

**Issue by abdulmannanbutt** [aryaxt/iOS-Slide-Menu#62]
I have to implement slide-menu with tabbar. Please guide me how could i do that?

Below is my code

//Initializinting Tabbar
        tabBarControler = [[UITabBarController alloc]init];

```
    [[UITabBar appearance] setTintColor:[UIColor whiteColor]];
    [[UITabBar appearance] setBarTintColor:[UIColor blackColor]];


    COHomeViewController *coHomeViewController = [[COHomeViewController alloc] initWithNibName:@"COHomeViewController" bundle:nil];

    UINavigationController *coHomeNavController = [[SlideNavigationController alloc] initWithRootViewController:coHomeViewController];
    coHomeNavController.navigationBarHidden = NO;
    coHomeNavController.navigationBar.translucent = NO;
    coHomeNavController.navigationBar.barTintColor = [UIColor blueHColor];
    coHomeNavController.navigationBar.tintColor = [UIColor whiteColor];
    coHomeNavController.navigationBar.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};


    COCalendarViewController *coCalenderViewController = [[COCalendarViewController alloc] initWithNibName:@"COCalendarViewController" bundle:nil];
    UINavigationController *coCalenderNavController = [[UINavigationController alloc] initWithRootViewController:coCalenderViewController];
    coCalenderNavController.navigationBarHidden = NO;
    coCalenderNavController.navigationBar.translucent = NO;
    coCalenderNavController.navigationBar.barTintColor = [UIColor blueHColor];
    coCalenderNavController.navigationBar.tintColor = [UIColor whiteColor];
    coCalenderNavController.navigationBar.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};

    COChatViewController *coChatViewController = [[COChatViewController alloc] initWithNibName:@"COChatViewController" bundle:nil];
    UINavigationController *coChatNavController = [[UINavigationController alloc] initWithRootViewController:coChatViewController];
    coChatNavController.navigationBarHidden = NO;
    coChatNavController.navigationBar.translucent = NO;
    coChatNavController.navigationBar.barTintColor = [UIColor blueHColor];
    coChatNavController.navigationBar.tintColor = [UIColor whiteColor];
    coChatNavController.navigationBar.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};

    COCareLogViewController *coCarelogViewController = [[COCareLogViewController alloc] initWithNibName:@"COCareLogViewController" bundle:nil];
    UINavigationController *coCarelogNavController = [[UINavigationController alloc] initWithRootViewController:coCarelogViewController];
    coCarelogNavController.navigationBarHidden = NO;
    coCarelogNavController.navigationBar.translucent = NO;
    coCarelogNavController.navigationBar.barTintColor = [UIColor blueHColor];
    coCarelogNavController.navigationBar.tintColor = [UIColor whiteColor];
    coCarelogNavController.navigationBar.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};

    COCareTeamViewController *coCareTeamViewController = [[COCareTeamViewController alloc] initWithNibName:@"COCareTeamViewController" bundle:nil];
    UINavigationController *coCareTeamNavController = [[UINavigationController alloc] initWithRootViewController:coCareTeamViewController];
    coCareTeamNavController.navigationBarHidden = NO;
    coCareTeamNavController.navigationBar.translucent = NO;
    coCareTeamNavController.navigationBar.barTintColor = [UIColor blueHColor];
    coCareTeamNavController.navigationBar.tintColor = [UIColor whiteColor];
    coCareTeamNavController.navigationBar.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor whiteColor]};



    self.tabBarControler.viewControllers = [NSArray arrayWithObjects:coHomeNavController,coCalenderNavController,coChatNavController,coCarelogNavController,coCareTeamNavController, nil];
    self.tabbarBackground = [[UIImageView alloc]initWithFrame:CGRectMake(0,0,320.0,50)];
    [self.tabbarBackground setImage:[UIImage imageNamed:@"home_selectedCO.png"]];
    [tabBarControler.tabBar addSubview:self.tabbarBackground];
    tabBarControler.delegate = self;


    COSlideViewController *coSlideViewController = [[COSlideViewController alloc] initWithNibName:@"COSlideViewController" bundle:nil];


    [SlideNavigationController sharedInstance].leftMenu = coSlideViewController;

    /// set animation type
    id <SlideNavigationContorllerAnimator> revealAnimator = [[SlideNavigationContorllerAnimatorScaleAndFade alloc] initWithMaximumFadeAlpha:.6 fadeColor:[UIColor blackColor] andMinimumScale:.7];
    [SlideNavigationController sharedInstance].menuRevealAnimator = revealAnimator;

    self.window.rootViewController = tabBarControler;

    [self.window makeKeyAndVisible];
```

Currently, I am getting following result. Only First tabbar item is responding to left swipe. But I want Nav Drawer till end. While other tabs are not swipable.

Please guide me.

![ios simulator screen shot 22-jul-2014 3 23 15 pm](https://cloud.githubusercontent.com/assets/960569/3656788/2eb674ba-118b-11e4-91e1-d33e8824fdb8.png)
![ios simulator screen shot 22-jul-2014 3 23 23 pm](https://cloud.githubusercontent.com/assets/960569/3656789/2ebb215e-118b-11e4-85c9-9b39a2536c7e.png)
![ios simulator screen shot 22-jul-2014 3 28 47 pm](https://cloud.githubusercontent.com/assets/960569/3656790/2ec3677e-118b-11e4-87c1-b51d4d94fdfa.png)

**Comment by jayjayesh** [comment]
thanks aryaxt,
this helps me to implement left menu on  UITabBarController.

**Comment by marcelghisi** [comment]
Hi, I have a UITabBarNavigationController and between the tabnavigationcontroller and the uiviewcontroller i added um uinavigationcontroller pointing to slidenavigationcontroller. but the left menu appear black. I didnot untherstand the way you did it in this post. In this post I got that I didnot the uinavigation controller, but instead I need to point the slidenavigationcontroller to uitabnavigationcontroller is thar right?

**Comment by kushalshah** [comment]
Hi abdulmannanbutt  and  aryaxt,
Your suggestions really helped me to develop such a thing. But I am facing another problem. My tabs and slidenavigation is working fine. But when I navigate to another page I lost tab bar, I only able to see slidenavigation menu image. What I want is to maintain tab bar through out the app. Can you guyz able to find the cause of it and able to suggest me the solution for it? Here I have attached screen shots. Second screen will appear when i click on button click.
![ios simulator screen shot 24-jul-2015 1 56 51 pm](https://cloud.githubusercontent.com/assets/2525672/8870456/f677bee0-320b-11e5-943c-2c379a608ce0.png)
![ios simulator screen shot 24-jul-2015 1 56 48 pm](https://cloud.githubusercontent.com/assets/2525672/8870455/f676dd86-320b-11e5-8811-76a30acbf663.png)

**Comment by sanif** [comment]
Hi, kushalshah. Me too facing the same situation. Did you figured it out how to solve this problem? if so please help me.

**Comment by mitsBhadeshiya** [comment]
hi @kushalshah  @sanif  i am also facing the same problem. Did you get any solution ?? then please tell me..

**Comment by technologers** [comment]
i am still facing the same problem ...plz help me. too

my whole team is frustrate

**Comment by aryaxt** [comment]
The only way this would work would be if the tabbar itself is inside SlideNavigationController, and in that case you need to manually add the menu button to your other navigationControllers

**Comment by MiteshMungara** [comment]
i want this app example code please help me...

**Comment by cculos** [comment]
@MiteshMungara I'm with you; please provide examples if possible as this is not proving to be straightforward

**Comment by anirudhsmarttechnica** [comment]
what i do when same option in tab bar and menu? ex:chat in menu also in tabbar

**Comment by aryaxt** [comment]
does it not work if you have SlideMenu as the nav, and tabbar as its root?

**Comment by coolcool1994** [comment]
If you follow the guide line, you would be able to implement SlideNavigationController into your tabbar. I did that successfully for almost everything, but "[SlideNavigationController sharedInstance].panGestureSideOffset = 60.0;" doesn't work. Did anyone able to get panGestureSideOffset to work in the tabbar set up?
