### ISSUE TITLE
App crashes when clicking Back from Second level push segue

### ISSUE THREAD

**Issue by gulsharan-pv** [aryaxt/iOS-Slide-Menu#67]
Hey Aryan, I really need some help on this issue that I'm facing. I'm currently working on app where I'm using your slide menu (great work, many thanks for sharing!). However, the app crashes when I try to come back from the 2nd push segue. A little help would be greatly appreciated as I've tried everything to get it to work, but have failed at all my attempts. TIA.

Here's what I'm doing:

This is how I'm switching to my view controller:

``` objectivec
    UIViewController *userHome = [[UIStoryboard userHomeStoryboard] instantiateViewControllerWithIdentifier: @"UserHomeViewController"];
    [[SlideNavigationController sharedInstance] popToRootAndSwitchToViewController:userHome withCompletion:nil];
```

UserHome view controller is defined on a separate storyboard as shown below:
![screen shot 2014-08-24 at 12 12 44 am](https://cloud.githubusercontent.com/assets/2501860/4022652/54f0e968-2b4d-11e4-9efd-059782f6939c.png)

_Problem_
I can easily navigate all the way to Page B. However, when I hit the Back button, I get the following error:

``` javascript
 *** -[UIView willRemoveSubview:]: message sent to deallocated instance 0x11375ad80
```

**Comment by gauravgoyal1211** [comment]
I get same error somebody have any solution for that ..........?
