### ISSUE TITLE
Allow gestures to be recognized simultaneously

### ISSUE THREAD

**Issue by yultide** [aryaxt/iOS-Slide-Menu#79]
Add the following to SlideNavigationController.m to allow other gestures to work with the slideout view.

- (BOOL)gestureRecognizer:(UIPanGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UISwipeGestureRecognizer *)otherGestureRecognizer
{
    return YES;
}

**Comment by lkmmmj** [comment]
I may get the same problem, When I create a Gesture Password viewcontroller, it does not work.
![image](https://cloud.githubusercontent.com/assets/527334/5899735/3d30c1b8-a59b-11e4-9463-a73d6fd9ebdd.png)

It seems that it cannot recognize my 'Pan' Gesture.

Could you help me?

**Comment by aryaxt** [comment]
@lkmmmj Can you test to see if the Devlope branch work for you or not? I have a fix in there that I'll test and merge to master soon

**Comment by aryaxt** [comment]
This was causing a lot of problems, I ended up removing it from 1.4.5. If you reallt need this feature just subclass override shouldRecognizeSimultaneouslyWithGestureRecognizer and return NO
