### ISSUE TITLE
My LeftMenuController is completely black.

### ISSUE THREAD

**Issue by ajcampbell** [aryaxt/iOS-Slide-Menu#81]
I have created a view and dragged a tableView into it. I've dragged a cell and giving it the identifier leftMenuCell. I've also set the class of the View to LeftMenuViewController and also given the storyboard the ID LeftMenuViewController.

I've enabled the slide menu on one of my tableView controllers and it slides as expected but the background revealed is completed black.

I'm using Swift / iOS8 and have imported the correct files using a bridging header file. All is working apart from the left menu controller which seems to show up black.

Would appreciate some help thanks for your time.

**Comment by KigenCoder** [comment]
For the ones using Objective C, following on @ajcampbell solution

UIStoryboard *mainStoryboard = [UIStoryboard storyboardWithName:@"Main" bundle: nil];
    
   LeftMenuViewController *leftMenu = [mainStoryboard instantiateViewControllerWithIdentifier:@"LeftMenuViewController"];
    
    [SlideNavigationController sharedInstance].leftMenu = leftMenu;

**Comment by 3r1k83** [comment]
Is not working anymore... i have black screen
