### ISSUE TITLE
UITableViewCell edit cell

### ISSUE THREAD

**Issue by Pades9** [aryaxt/iOS-Slide-Menu#90]
Hi guys,

can you help me I have UITableView but editingStyleForRowAtIndexPath(Delete) working unusually. I swipe left 10times but delete button show me only 1 time absolute random. I have push on UITableViewCell but it works fine. Where can be the problem? Of course I am using SlideMenu. Thank you for replies.

**Comment by aryaxt** [comment]
This was causing a lot of problems, I ended up removing it from 1.4.5

**Comment by seanLee** [comment]
@aryaxt I met this problem too.What can I do if the right menu is scrollview with the horizontal direction?I have tried this way,but it did not work to my purpose.
